### ISSUE TITLE
[Insight] YAML files should not contain syntax error - in .travis.yml, line 31

### ISSUE THREAD

**Issue by hubdotcom** [sendgrid/sendgrid-php#153]
**[in .travis.yml, line 31](https://github.com/sendgrid/sendgrid-php/blob/12d24853ca617b0aa27031a12e886e6a0c4d2190/.travis.yml#L31)**

> Malformed inline YAML string ('%{repository}) at line 31 (near "- '%{repository}").

```
notifications:
  hipchat:
    rooms:
      secure: l4RUOBY44kVhSxx54NU3cmvn598rRMB7Y272Ct/W0fBm1tdGncp42A/rwg7JkiZH9EWXs3tKtoSjqw5xT6QeScUGQDdykS5QVO8lEIkDRGD4WwQ3VDJmRy1+04WtgqFEK8SyYTCcCl4ZJ0rtOcJZgDMvigkOJuLxwGXTDuvfu1k=
    template:
    - '<a href="https://travis-ci.org/%{repository}/builds/%{build_id}">%{repository}
      Build %{build_number}</a> on branch <i>%{branch}</i> by %{author}: <strong>%{message}</strong><a href="https://github.com/sendgrid/docs/commits/%{commit}">View on GitHub</a>'
    format: html
    notify: true

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/19f20f51-a672-4115-adab-6e06c80df7d9/analyses/18)_
